import { AfterViewInit, Component, ElementRef, OnDestroy, ViewChild, inject, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { Chart, registerables } from 'chart.js';
import { DashboardService, RestaurantStore } from '../core/store';
import { FALLBACK_IMAGE } from '../core/mock-data';
import { money, orderTotal } from '../core/models';
Chart.register(...registerables);

@Component({selector:'app-dashboard',imports:[RouterLink],template:`
<div class="page dashboard-page">@if(loading()){<div class="loading-cover"><div class="skeleton skeleton-title"></div><div class="skeleton skeleton-subtitle"></div><div class="skeleton-cards"><div class="skeleton skeleton-kpi"></div><div class="skeleton skeleton-kpi"></div><div class="skeleton skeleton-kpi"></div><div class="skeleton skeleton-kpi"></div></div><div class="skeleton-panels"><div class="skeleton"></div><div class="skeleton"></div></div></div>}<div class="page-heading"><div><div class="eyebrow"><span class="eyebrow-line"></span> RESUMEN GENERAL</div><h1>Buenos días, Arnold <span class="wave">👋</span></h1><p>Aquí tienes un resumen de lo que está ocurriendo hoy en tu restaurante.</p></div><a class="btn btn-primary" routerLink="/pedidos/nuevo"><span class="material-symbols-rounded">add</span>Nuevo pedido</a></div>
<div class="date-strip"><span class="material-symbols-rounded">calendar_today</span><strong>Hoy, {{today}}</strong><span class="date-divider"></span><span>Actualizado en tiempo real</span><span class="live-dot"></span></div>
<div class="kpi-grid"><div class="kpi-card" style="--card-accent:#c2410c"><div class="kpi-top"><span>Ventas de hoy</span><div class="kpi-icon"><span class="material-symbols-rounded">payments</span></div></div><div class="kpi-value">{{money(stats.stats().sales)}}</div><div class="kpi-bottom"><span class="growth"><span class="material-symbols-rounded">trending_up</span>12.5%</span><span>vs. ayer</span><svg viewBox="0 0 112 38" class="spark"><path d="M0 31 Q12 27 20 29 T39 19 T59 22 T78 10 T112 4"/></svg></div></div><div class="kpi-card" style="--card-accent:#3b82f6"><div class="kpi-top"><span>Pedidos</span><div class="kpi-icon"><span class="material-symbols-rounded">receipt_long</span></div></div><div class="kpi-value">{{stats.stats().orders}}</div><div class="kpi-bottom"><span class="growth"><span class="material-symbols-rounded">trending_up</span>8%</span><span>vs. ayer</span><svg viewBox="0 0 112 38" class="spark"><path d="M0 29 Q14 25 22 31 T43 16 T62 18 T83 8 T112 5"/></svg></div></div><div class="kpi-card" style="--card-accent:#8b5cf6"><div class="kpi-top"><span>Mesas ocupadas</span><div class="kpi-icon"><span class="material-symbols-rounded">table_restaurant</span></div></div><div class="kpi-value">{{stats.stats().occupied}} <span>/ {{stats.stats().tableCount}}</span></div><div class="kpi-bottom"><span class="occupancy-bar"><i [style.width.%]="stats.stats().occupied/stats.stats().tableCount*100"></i></span><span>Ocupación actual</span></div></div><div class="kpi-card" style="--card-accent:#16a34a"><div class="kpi-top"><span>Ticket promedio</span><div class="kpi-icon"><span class="material-symbols-rounded">confirmation_number</span></div></div><div class="kpi-value">{{money(stats.stats().average)}}</div><div class="kpi-bottom"><span class="growth"><span class="material-symbols-rounded">trending_up</span>5.2%</span><span>vs. ayer</span><svg viewBox="0 0 112 38" class="spark"><path d="M0 33 Q12 30 25 24 T47 21 T69 16 T91 9 T112 3"/></svg></div></div></div>
<div class="analytics-grid"><section class="surface chart-card"><div class="section-heading"><div><h2>Ventas de la semana</h2><p>Rendimiento de los últimos 7 días</p></div><span class="select-look">Esta semana <span class="material-symbols-rounded">expand_more</span></span></div><div class="sales-amount">S/ 9,700.00 <span class="growth">+12.5% <span>vs. semana pasada</span></span></div><div class="chart-wrap"><canvas #salesChart aria-label="Gráfico de ventas semanales"></canvas></div></section><section class="surface status-chart-card"><div class="section-heading"><div><h2>Pedidos por estado</h2><p>Distribución de hoy</p></div><button class="icon-btn" aria-label="Más opciones"><span class="material-symbols-rounded">more_horiz</span></button></div><div class="donut-wrap"><canvas #statusChart aria-label="Gráfico de pedidos por estado"></canvas><div class="donut-center"><strong>48</strong><span>Pedidos</span></div></div><div class="chart-legend"><span><i style="background:#f59e0b"></i>Pendientes <strong>12</strong></span><span><i style="background:#c2410c"></i>Preparando <strong>15</strong></span><span><i style="background:#3b82f6"></i>Listos <strong>8</strong></span><span><i style="background:#16a34a"></i>Entregados <strong>13</strong></span></div></section></div>
<div class="lower-grid"><section class="surface bestsellers"><div class="section-heading"><div><h2>Platos más vendidos</h2><p>Los favoritos de tus clientes</p></div><a routerLink="/catalogo" class="text-link">Ver catálogo <span class="material-symbols-rounded">arrow_forward</span></a></div>@for(dish of store.topDishes();track dish.id){<div class="best-item"><span class="rank">0{{$index+1}}</span><img [src]="dish.image" [alt]="dish.name" loading="lazy" (error)="fallback($event)"><div class="best-info"><strong>{{dish.name}}</strong><small>{{categoryName(dish.categoryId)}}</small></div><div class="best-stats"><strong>{{dish.sold}} pedidos</strong><span class="mini-progress"><i [style.width.%]="dish.sold/85*100"></i></span></div></div>}</section><section class="surface recent"><div class="section-heading"><div><h2>Últimos pedidos</h2><p>Actividad reciente del restaurante</p></div><a routerLink="/pedidos" class="text-link">Ver todos <span class="material-symbols-rounded">arrow_forward</span></a></div><div class="table-scroll"><table><thead><tr><th>Pedido</th><th>Canal</th><th>Cliente</th><th>Total</th><th>Estado</th><th>Hora</th><th></th></tr></thead><tbody>@for(order of store.recentOrders().slice(0,5);track order.id){<tr><td><a class="order-link" [routerLink]="[order.channel==='delivery'?'/delivery':'/pedidos',order.id]">#PED-{{order.id}}</a></td><td>{{order.channel==='delivery'?'Delivery':'Mesa '+pad(order.tableId)}}</td><td>{{order.customer}}</td><td class="bold">{{money(orderTotal(order))}}</td><td><span class="badge" [class]="'badge '+statusClass(order.status)"><i></i>{{order.status}}</span></td><td>{{time(order.createdAt)}}</td><td><a [routerLink]="[order.channel==='delivery'?'/delivery':'/pedidos',order.id]" class="table-action" aria-label="Ver pedido"><span class="material-symbols-rounded">arrow_forward</span></a></td></tr>}</tbody></table></div></section></div></div>`})
export class DashboardPage implements AfterViewInit,OnDestroy {
  readonly loading=signal(true);
  readonly store=inject(RestaurantStore);readonly stats=inject(DashboardService);readonly money=money;readonly orderTotal=orderTotal;readonly today=new Intl.DateTimeFormat('es-PE',{weekday:'long',day:'numeric',month:'long'}).format(new Date());
  @ViewChild('salesChart') salesCanvas!:ElementRef<HTMLCanvasElement>;@ViewChild('statusChart') statusCanvas!:ElementRef<HTMLCanvasElement>;private charts:Chart[]=[];
  constructor(){setTimeout(()=>this.loading.set(false),420);}
  ngAfterViewInit(){this.charts.push(new Chart(this.salesCanvas.nativeElement,{type:'line',data:{labels:['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'],datasets:[{data:this.stats.stats().weekSales,borderColor:'#c2410c',backgroundColor:'rgba(194,65,12,.07)',fill:true,tension:.42,borderWidth:3,pointRadius:4,pointHoverRadius:7,pointBackgroundColor:'#fff',pointBorderColor:'#c2410c',pointBorderWidth:2}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{backgroundColor:'#17212f',padding:12,displayColors:false,callbacks:{label:ctx=>money(Number(ctx.raw))}}},scales:{x:{grid:{display:false},border:{display:false},ticks:{color:'#94a3b8'}},y:{grid:{color:'#f1f3f6'},border:{display:false},ticks:{color:'#94a3b8',callback:v=>`S/ ${v}`}}}}}));this.charts.push(new Chart(this.statusCanvas.nativeElement,{type:'doughnut',data:{labels:['Pendientes','Preparando','Listos','Entregados'],datasets:[{data:[12,15,8,13],backgroundColor:['#f59e0b','#c2410c','#3b82f6','#16a34a'],borderWidth:5,borderColor:'#fff',hoverOffset:6}]},options:{responsive:true,maintainAspectRatio:false,cutout:'77%',plugins:{legend:{display:false}}}}));}
  ngOnDestroy(){this.charts.forEach(c=>c.destroy());}
  categoryName(id:number){return this.store.categories().find(c=>c.id===id)?.name??'';} pad(id:number){return String(id).padStart(2,'0');}time(value:string){return new Date(value).toLocaleTimeString('es-PE',{hour:'2-digit',minute:'2-digit'});}statusClass(value:string){return `status-${value.toLowerCase()}`;}fallback(event:Event){(event.target as HTMLImageElement).src=FALLBACK_IMAGE;}
}
