import { Component, inject, signal } from '@angular/core';
import { Router, RouterLink, RouterLinkActive, RouterOutlet, NavigationEnd } from '@angular/router';
import { filter } from 'rxjs';
import { MatTooltipModule } from '@angular/material/tooltip';
import { CurrentUserService, RestaurantStore } from '../core/store';
import { ThemeService } from '../core/theme';

@Component({selector:'app-layout',imports:[RouterOutlet,RouterLink,RouterLinkActive,MatTooltipModule],template:`
<div class="shell" [class.compact]="collapsed()">
  <div class="mobile-scrim" [class.open]="mobileOpen()" (click)="mobileOpen.set(false)"></div>
  <aside class="sidebar" [class.mobile-open]="mobileOpen()">
    <div class="brand"><div class="brand-mark"><span class="material-symbols-rounded">restaurant</span></div><div class="brand-copy"><strong>Sazón <em>&</em> Raíz</strong><small>RESTAURANT OS</small></div><button class="collapse-btn icon-btn" (click)="collapsed.set(!collapsed())" [attr.aria-label]="collapsed()?'Expandir menú':'Contraer menú'"><span class="material-symbols-rounded">dock_to_right</span></button></div>
    <div class="nav-section">GENERAL</div>
    <nav aria-label="Navegación principal">@for(item of mainNav;track item.path){<a [routerLink]="item.path" routerLinkActive="active" [routerLinkActiveOptions]="{exact:item.path==='/dashboard'}" [matTooltip]="item.label" [matTooltipDisabled]="!collapsed()" matTooltipPosition="right" (click)="mobileOpen.set(false)"><span class="material-symbols-rounded">{{item.icon}}</span><span class="nav-label">{{item.label}}</span></a>}</nav>
    <div class="nav-section second-section">ADMINISTRACIÓN</div>
    <nav aria-label="Administración">@for(item of adminNav;track item.path){<a [routerLink]="item.path" routerLinkActive="active" [matTooltip]="item.label" [matTooltipDisabled]="!collapsed()" matTooltipPosition="right" (click)="mobileOpen.set(false)"><span class="material-symbols-rounded">{{item.icon}}</span><span class="nav-label">{{item.label}}</span></a>}</nav>
    <div class="sidebar-bottom"><a routerLink="/ordenar" class="help-card customer-link"><span class="material-symbols-rounded">storefront</span><strong>Menú para clientes</strong><p>Abre la experiencia de pedidos delivery.</p></a><div class="sidebar-profile"><div class="avatar">{{initials}}</div><div class="profile-copy"><strong>{{current.user().firstName}} {{current.user().lastName}}</strong><small>{{current.user().role}}</small></div><span class="material-symbols-rounded profile-more">more_vert</span></div></div>
  </aside>
  <div class="workspace">
    <header class="topbar"><div class="top-left"><button class="icon-btn mobile-menu" aria-label="Abrir menú" (click)="mobileOpen.set(true)"><span class="material-symbols-rounded">menu</span></button><div class="breadcrumb"><span>Workspace</span><span class="material-symbols-rounded">chevron_right</span><strong>{{pageTitle()}}</strong></div></div><div class="top-actions"><button class="icon-btn theme-toggle" type="button" (click)="theme.toggle()" [attr.aria-label]="theme.theme()==='dark'?'Cambiar a tema claro':'Cambiar a tema oscuro'" [attr.title]="theme.theme()==='dark'?'Tema claro':'Tema oscuro'" [attr.aria-pressed]="theme.theme()==='dark'"><span class="material-symbols-rounded">{{theme.theme()==='dark'?'light_mode':'dark_mode'}}</span></button><div class="top-search"><span class="material-symbols-rounded">search</span><input aria-label="Buscar módulos" placeholder="Buscar en el sistema..." (keydown.enter)="search($event)"><kbd>↵</kbd></div><div class="dropdown-anchor"><button class="icon-btn notification-button" aria-label="Notificaciones" (click)="notificationsOpen.set(!notificationsOpen()); profileOpen.set(false)"><span class="material-symbols-rounded">notifications</span>@if(store.unread()){<i></i>}</button>@if(notificationsOpen()){<div class="dropdown notification-panel"><div class="dropdown-head"><strong>Notificaciones</strong><button class="text-btn" (click)="store.markNotificationsRead()">Marcar leídas</button></div>@for(note of store.notifications();track note.id){<div class="notification-item" [class.unread]="!note.read"><div class="notification-icon"><span class="material-symbols-rounded">{{note.icon}}</span></div><div><strong>{{note.title}}</strong><p>{{note.detail}}</p><small>{{note.time}}</small></div></div>}</div>}</div><div class="top-divider"></div><div class="dropdown-anchor"><button class="user-trigger" (click)="profileOpen.set(!profileOpen()); notificationsOpen.set(false)" aria-label="Menú de usuario"><div class="avatar">{{initials}}</div><span class="user-caption"><strong>{{current.user().firstName}} {{current.user().lastName}}</strong><small>{{current.user().role}}</small></span><span class="material-symbols-rounded">expand_more</span></button>@if(profileOpen()){<div class="dropdown user-menu"><a routerLink="/perfil" (click)="profileOpen.set(false)"><span class="material-symbols-rounded">person</span>Mi perfil</a><a routerLink="/configuracion" (click)="profileOpen.set(false)"><span class="material-symbols-rounded">settings</span>Configuración</a><a routerLink="/ordenar" (click)="profileOpen.set(false)"><span class="material-symbols-rounded">storefront</span>Ver menú público</a></div>}</div></div></header>
    <main class="page-content"><router-outlet /></main>
  </div>
</div>`})
export class AppLayout {
  readonly current=inject(CurrentUserService); readonly store=inject(RestaurantStore); readonly theme=inject(ThemeService); private router=inject(Router);
  readonly collapsed=signal(false);readonly mobileOpen=signal(false);readonly notificationsOpen=signal(false);readonly profileOpen=signal(false);readonly pageTitle=signal('Dashboard');
  readonly mainNav=[{path:'/dashboard',label:'Dashboard',icon:'dashboard'},{path:'/pedidos',label:'Pedidos',icon:'receipt_long'},{path:'/delivery',label:'Delivery',icon:'two_wheeler'},{path:'/motorizado',label:'Motorizado',icon:'delivery_dining'},{path:'/mesas',label:'Mesas',icon:'table_restaurant'},{path:'/catalogo',label:'Catálogo',icon:'menu_book'}];
  readonly adminNav=[{path:'/categorias',label:'Categorías',icon:'category'},{path:'/usuarios',label:'Usuarios',icon:'group'},{path:'/configuracion',label:'Configuración',icon:'settings'}];
  get initials(){const u=this.current.user();return `${u.firstName[0]??'A'}${u.lastName[0]??'A'}`;}
  constructor(){this.router.events.pipe(filter(e=>e instanceof NavigationEnd)).subscribe(()=>{const path=this.router.url.split('/')[1];this.pageTitle.set([...this.mainNav,...this.adminNav,{path:'/perfil',label:'Mi perfil',icon:'person'}].find(n=>n.path==='/'+path)?.label??'Dashboard');this.profileOpen.set(false);this.notificationsOpen.set(false);});}
  search(event:Event){const value=(event.target as HTMLInputElement).value.toLowerCase();const item=[...this.mainNav,...this.adminNav].find(n=>n.label.toLowerCase().includes(value));if(item)void this.router.navigateByUrl(item.path);}
}
